# Generated by Django 4.1.3 on 2024-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, null=True, upload_to='cover_page/')),
                ('description', models.CharField(max_length=500)),
                ('visibility', models.BooleanField(default=True)),
                ('cost', models.IntegerField()),
                ('year_publish', models.IntegerField()),
                ('file', models.FileField(default=None, null=True, upload_to='books/')),
            ],
        ),
    ]
