# Generated by Django 4.1.3 on 2024-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('whatsapp_active', models.BooleanField(default=False)),
                ('whatsapp_inactive', models.BooleanField(default=False)),
                ('blaster_sent', models.BooleanField(default=False)),
                ('blaster_notsent', models.BooleanField(default=False)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
